version: '3'
services:
  postgres:
    image: 'bitnami/postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=bycoders
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - app-net

  server:
    build:
      context: .
      dockerfile: 'packages/server/Dockerfile'
    container_name: bycoders-challenge-server
    ports:
      - 3333:3333
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - "postgres"
    networks:
      - app-net

  web:
    build:
      context: .
      dockerfile: 'packages/web/Dockerfile'
    container_name: bycoders-challenge-web
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
