version: '3'
services:
  server:
    build:
      context: .
      dockerfile: 'packages/server/Dockerfile'
    container_name: bycoders-challenge-server
    ports:
      - 3333:3333
    volumes:
      - .:/app
      - /app/node_modules
  web:
    build:
      context: .
      dockerfile: 'packages/web/Dockerfile'
    container_name: bycoders-challenge-web
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
